### ISSUE TITLE
Can't connect redux store

### ISSUE THREAD

**Issue by zsirfs** [brianegan/dart_redux_epics#18] opened 2018-12-19 08:05 UTC
![image](https://user-images.githubusercontent.com/22249411/50206835-9d00ae00-03a7-11e9-9a14-dfa50e855023.png)

This is my epic class.

```dart
final githubApi = GithubApi();
  var store = Store<AppState>(
    appReducer,
    initialState: AppState(
      sharedPreferences: initInfo.sharedPreferences,
    ),
    middleware: [
      EpicMiddleware<AppState>(AppEpic(githubApi)),
    ],
  );
```

![image](https://user-images.githubusercontent.com/22249411/50206910-e650fd80-03a7-11e9-8dba-7a71fe7d7275.png)

Can't dispatch the this action.

**Comment by MichaelMarner** [comment] 2019-01-02 01:08
What errors/exceptions are you getting?

**Comment by brianegan** [comment] 2019-01-07 12:15
Hey there -- back from vacay. In this case, you're probably getting a type error. `asyncMap` expects that you'll return a `Future` not a `Stream`. To fix this, you can do one of two things:

  1. Use RxDart, which includes the `flatMap` operator. Use `flatMap` in place of `asyncMap`.
  2. Make the `call` function your `async*` function and just do everything in there.

Example:

```dart
class AppEpic implements EpicClass<AppState> {
  Stream call(Stream actions, EpicStore<AppState> store) async* {
    await for (action in actions) {
      if (action is AppInitAction) {
        // do _load method stuff here
      }
    }
  }
}
```

**Comment by zsirfs** [comment] 2019-01-08 01:16
@brianegan Ok. I will try.

**Comment by brianegan** [comment] 2019-02-13 11:44
Hey @zsirfs, gonna close this for now, but please feel free to reopen if the issue isn't resolved :)

**Closed by brianegan** 2019-02-13 11:44 UTC
